
export const TEAM_LOGOS: Record<string, string> = {
    ARI: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
    ATL: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
    BAL: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
    BUF: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
    CAR: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
    CHI: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png',
    CIN: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
    CLE: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
    DAL: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
    DEN: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
    DET: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
    GB: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
    HOU: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
    IND: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
    JAX: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
    KC: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
    LAC: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
    LAR: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
    LV: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
    MIA: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
    MIN: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
    NE: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
    NO: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
    NYG: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
    NYJ: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
    PHI: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
    PIT: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
    SEA: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
    SF: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
    TB: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
    TEN: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
    WAS: 'https://a.espncdn.com/i/teamlogos/nfl/500/was.png',
};

export const TEAM_NAMES: Record<string, string> = {
    ARI: 'Arizona Cardinals',
    ATL: 'Atlanta Falcons',
    BAL: 'Baltimore Ravens',
    BUF: 'Buffalo Bills',
    CAR: 'Carolina Panthers',
    CHI: 'Chicago Bears',
    CIN: 'Cincinnati Bengals',
    CLE: 'Cleveland Browns',
    DAL: 'Dallas Cowboys',
    DEN: 'Denver Broncos',
    DET: 'Detroit Lions',
    GB: 'Green Bay Packers',
    HOU: 'Houston Texans',
    IND: 'Indianapolis Colts',
    JAX: 'Jacksonville Jaguars',
    KC: 'Kansas City Chiefs',
    LAC: 'Los Angeles Chargers',
    LAR: 'Los Angeles Rams',
    LV: 'Las Vegas Raiders',
    MIA: 'Miami Dolphins',
    MIN: 'Minnesota Vikings',
    NE: 'New England Patriots',
    NO: 'New Orleans Saints',
    NYG: 'New York Giants',
    NYJ: 'New York Jets',
    PHI: 'Philadelphia Eagles',
    PIT: 'Pittsburgh Steelers',
    SEA: 'Seattle Seahawks',
    SF: 'San Francisco 49ers',
    TB: 'Tampa Bay Buccaneers',
    TEN: 'Tennessee Titans',
    WAS: 'Washington Commanders',
};
