-- AUTO-GENERATED BY contracts/compile.py
-- DO NOT EDIT MANUALLY

-- Raw game logs from Pro-Football-Reference
CREATE TABLE IF NOT EXISTS silver_pfr_game_logs (
    player_name VARCHAR,
    team VARCHAR,
    year INTEGER,
    game_url VARCHAR,
    Passing_Yds VARCHAR,
    Rushing_Yds VARCHAR,
    Receiving_Yds VARCHAR,
    Passing_TD VARCHAR,
    Rushing_TD VARCHAR,
    Receiving_TD VARCHAR,
    Sacks VARCHAR,
    Interceptions VARCHAR
);

-- Player penalty statistics
CREATE TABLE IF NOT EXISTS silver_penalties (
    player_name_short VARCHAR,
    team VARCHAR,
    year INTEGER,
    penalty_count INTEGER,
    penalty_yards INTEGER
);

-- Contract data from Spotrac
CREATE TABLE IF NOT EXISTS silver_spotrac_contracts (
    player_name VARCHAR,
    team VARCHAR,
    year INTEGER,
    position VARCHAR,
    cap_hit_millions FLOAT,
    dead_cap_millions FLOAT,
    signing_bonus_millions FLOAT,
    age INTEGER
);

-- Positional ranking data
CREATE TABLE IF NOT EXISTS silver_spotrac_rankings (
    player_name VARCHAR,
    year INTEGER,
    ranking_cap_hit_millions FLOAT
);

-- Team-level cap and performance data
CREATE TABLE IF NOT EXISTS silver_team_cap (
    team VARCHAR,
    year INTEGER,
    win_pct FLOAT
);

-- Static player attributes
CREATE TABLE IF NOT EXISTS silver_player_metadata (
    full_name VARCHAR,
    birth_date VARCHAR,
    college VARCHAR,
    draft_round INTEGER,
    draft_pick INTEGER,
    experience_years INTEGER
);

-- NFLPA Merchandise sales rankings
CREATE TABLE IF NOT EXISTS silver_player_merch (
    Player VARCHAR,
    Rank INTEGER
);

-- Forbes team valuation data
CREATE TABLE IF NOT EXISTS silver_team_finance (
    Team VARCHAR,
    Year INTEGER,
    Revenue_M FLOAT,
    OperatingIncome_M FLOAT
);

-- Salary breakdown
CREATE TABLE IF NOT EXISTS silver_spotrac_salaries (
    player_name VARCHAR,
    team VARCHAR,
    year INTEGER,
    position VARCHAR,
    "dead cap" VARCHAR
);

-- Draft history data
CREATE TABLE IF NOT EXISTS silver_pfr_draft_history (
    player_name VARCHAR,
    team VARCHAR,
    year INTEGER,
    draft_round INTEGER,
    draft_pick INTEGER
);

-- Gold Layer: Player Efficiency Analytics
CREATE TABLE IF NOT EXISTS fact_player_efficiency (
    player_name VARCHAR,
    team VARCHAR,
    year INTEGER,
    position VARCHAR,
    age INTEGER,
    college VARCHAR,
    draft_round INTEGER,
    draft_pick INTEGER,
    experience_years INTEGER,
    games_played INTEGER,
    availability_rating FLOAT,
    total_pass_yds FLOAT,
    total_rush_yds FLOAT,
    total_rec_yds FLOAT,
    total_tds INTEGER,
    total_penalty_count INTEGER,
    total_penalty_yards INTEGER,
    total_sacks FLOAT,
    total_int FLOAT,
    cap_hit_millions FLOAT,
    dead_cap_millions FLOAT,
    signing_bonus_millions FLOAT,
    potential_dead_cap_millions FLOAT,
    edce_risk FLOAT,
    fair_market_value FLOAT,
    ml_risk_score FLOAT
);
