// AUTO-GENERATED BY contracts/compile.py
// DO NOT EDIT MANUALLY

/** Raw game logs from Pro-Football-Reference */
export interface SilverPfrGameLogs {
  /** Player active name */
  player_name: string;
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Unique URL per game */
  game_url: string;
  /** Passing Yards (raw) */
  Passing_Yds: string;
  /** Rushing Yards (raw) */
  Rushing_Yds: string;
  /** Receiving Yards (raw) */
  Receiving_Yds: string;
  /** Passing Touchdowns (raw) */
  Passing_TD: string;
  /** Rushing Touchdowns (raw) */
  Rushing_TD: string;
  /** Receiving Touchdowns (raw) */
  Receiving_TD: string;
  /** Sacks (raw) */
  Sacks: string;
  /** Interceptions (raw) */
  Interceptions: string;
}

/** Player penalty statistics */
export interface SilverPenalties {
  /** Short name (e.g. T.Brady) */
  player_name_short: string;
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Number of penalties */
  penalty_count: number;
  /** Yards lost to penalties */
  penalty_yards: number;
}

/** Contract data from Spotrac */
export interface SilverSpotracContracts {
  /** Player full name */
  player_name: string;
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Player position */
  position: string;
  /** Cap hit in millions */
  cap_hit_millions: number;
  /** Dead cap in millions */
  dead_cap_millions: number;
  /** Signing bonus in millions */
  signing_bonus_millions: number;
  /** Player age */
  age: number;
}

/** Positional ranking data */
export interface SilverSpotracRankings {
  /** Player full name */
  player_name: string;
  /** Season year */
  year: number;
  /** Ranked cap hit */
  ranking_cap_hit_millions: number;
}

/** Team-level cap and performance data */
export interface SilverTeamCap {
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Winning percentage */
  win_pct: number;
}

/** Static player attributes */
export interface SilverPlayerMetadata {
  /** Player full name */
  full_name: string;
  /** DOB (YYYY-MM-DD) */
  birth_date: string;
  /** College attended */
  college: string;
  /** Draft round */
  draft_round: number;
  /** Overall pick number */
  draft_pick: number;
  /** Years in league */
  experience_years: number;
}

/** NFLPA Merchandise sales rankings */
export interface SilverPlayerMerch {
  /** Player name */
  Player: string;
  /** Sales rank */
  Rank: number;
}

/** Forbes team valuation data */
export interface SilverTeamFinance {
  /** Team name/city */
  Team: string;
  /** Fiscal year */
  Year: number;
  /** Revenue in millions */
  Revenue_M: number;
  /** Operating income in millions */
  OperatingIncome_M: number;
}

/** Salary breakdown */
export interface SilverSpotracSalaries {
  /** Player name */
  player_name: string;
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Player position */
  position: string;
  /** Raw dead cap string */
  "dead cap": string;
}

/** Draft history data */
export interface SilverPfrDraftHistory {
  /** Player name */
  player_name: string;
  /** Drafting team */
  team: string;
  /** Draft year */
  year: number;
  /** Round */
  draft_round: number;
  /** Pick */
  draft_pick: number;
}

/** Gold Layer: Player Efficiency Analytics */
export interface FactPlayerEfficiency {
  /** Player active name */
  player_name: string;
  /** Team abbreviation */
  team: string;
  /** Season year */
  year: number;
  /** Primary position */
  position: string;
  /** Player age */
  age: number;
  /** College attended */
  college: string;
  /** Draft round */
  draft_round: number;
  /** Overall pick number */
  draft_pick: number;
  /** Years in league */
  experience_years: number;
  /** Games played count */
  games_played: number;
  /** Availability score (0-1) */
  availability_rating: number;
  /** Total passing yards */
  total_pass_yds: number;
  /** Total rushing yards */
  total_rush_yds: number;
  /** Total receiving yards */
  total_rec_yds: number;
  /** Total touchdowns */
  total_tds: number;
  /** Total penalties */
  total_penalty_count: number;
  /** Total penalty yards */
  total_penalty_yards: number;
  /** Total Sacks */
  total_sacks: number;
  /** Total Interceptions */
  total_int: number;
  /** Cap hit (M) */
  cap_hit_millions: number;
  /** Dead cap (M) */
  dead_cap_millions: number;
  /** Signing bonus (M) */
  signing_bonus_millions: number;
  /** Projected dead cap risk */
  potential_dead_cap_millions: number;
  /** Target variable: Effective Dead Cap Exposure */
  edce_risk: number;
  /** Calculated FMV score */
  fair_market_value: number;
  /** ML-predicted risk score */
  ml_risk_score: number;
}
